name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Install Cowsay programm
              run: sudo apt install cowsay -y

            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

            - name: Test file exist
              run: grep -i "dragon" dragon.txt

            - name: Read File
              run: cat dragon.txt

            - name: List Repo Files
              run: ls -ltra

